Improve typing
termcolor/termcolor pull request #44
Opened 2023-04-18 16:32 UTC by marcin-serwin

This PR introduces two changes to the declared type signatures:
1. The allowed colors, highlights, and attributes are now checked against defined string literals. This means that, e.g., `cprint("hello", "orange")` will result in
   ```
   error: Argument 2 to "cprint" has incompatible type "Literal['orange']"; expected "Optional[Literal['black', 'grey', 'red', 'green', 'yellow', 'blue', 'magenta', 'cyan', 'light_grey', 'dark_grey', 'light_red', 'light_green', 'light_yellow', 'light_blue', 'light_magenta', 'light_cyan', 'white']]"
   ```
   when using type checker.
2. The type of first argument of `colored` and `cprint` was relaxed to accept `object`s and not just `str`ings. This makes `cprint` more in line with `print`, which accepts arbitrary objects and fixes the example in README which reads
    ```python
    for i in range(10):
        cprint(i, "magenta", end=" ")
    ```
    which currently results in `error: Argument 1 to "cprint" has incompatible type "int"; expected "str"` when running through mypy.

2023-04-22 17:09 UTC, hugovk requested changes
Thanks for the PR! Here's a couple of suggestions.

2023-04-22 17:09 UTC, hugovk commented on src/termcolor/_types.py
> +    "dark",
Rather than duplicating all these values from `termcolor.py`, can we re-use them?

2023-04-22 17:09 UTC, hugovk commented on src/termcolor/termcolor.py
> +    if _can_do_colour():
Please keep the earlier structure to return early and reduce indentation.

2023-10-03 18:46 UTC, vidhanio commented
any way this could be merged? this seems like an amazing upgrade for usability, and the only blocker seems to be impossible to do in the current state of python typing.

2023-10-13 14:45 UTC, hugovk commented
Thanks for ping. If the conflicts are resolved, I'll take another look.

2023-10-14 06:29 UTC, hugovk approved these changes

2023-10-14 06:29 UTC, merged