added colorAdd()
termcolor/termcolor pull request #53
Opened 2023-08-12 16:34 UTC by canTuncPekkan

colorAdd() allows the user to add a new color with RGB

example;
colorAdd("Light Coral", (240, 128, 128))

now you can use "Light Coral" as a color

2023-08-12 16:46 UTC, canTuncPekkan commented
umm I am new to GitHub and this is the first time this happened, why has it failed

2023-08-13 17:54 UTC, hugovk commented
Thanks for the PR!

These are some automated checks to make sure tests pass and some code quality/linters are happy.

I added a changelog label, so that's now happy. There's still some lint things to check, but I'll add a review with some other suggestions first.

2023-08-13 18:04 UTC, hugovk requested changes
Please can you add some unit tests so we know this is working correctly?

2023-08-13 18:04 UTC, hugovk commented on src/termcolor/termcolor.py
> +        RGB (R, G, B): the RGB value of the collor you want to add. Defaults to None.
```suggestion
        color (str): color name
        rgb (R, G, B): the RGB value of the color you want to add. Defaults to None.
```

2023-08-13 18:04 UTC, hugovk commented on src/termcolor/termcolor.py
> +    if not RGB == None:
```suggestion
    if not rgb:
```

2023-08-13 18:04 UTC, hugovk commented on src/termcolor/termcolor.py
> +        light_magenta, light_cyan, and all collors added by addCollor().
```suggestion
        light_magenta, light_cyan, and any colors added via add_color().
```

2023-11-12 10:42 UTC, hugovk commented
Reminder that this needs some updates. Let me know if you've any questions. Thanks!

2024-09-14 09:55 UTC, hugovk commented
Closing due to inactivity, but do let me know if you'd like help and we can re-open.

2024-09-14 09:55 UTC, closed without merging